name = "newsnow"  # 你的项目名称
type = "javascript"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"  # 替换为你创建的数据库名称
database_id = "cd08575b-e99e-415d-b415-14f3629fa380"      # 替换为你创建的数据库 ID
