name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2025-3-30"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"
database_id = "cd08575b-e99e-415d-b415-14f3629fa380"
